# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [6]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [7]:
x.size


10

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [9]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x7fda0918be80>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [12]:
x=np.zeros(10)
x[5]=1
x

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [15]:
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [18]:
x=np.arange(10,20)
x[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [20]:
x=np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [21]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [22]:
x=np.random.randn(27).reshape(3,3,3)
x

array([[[ 0.26128572, -0.46760819,  2.67171889],
        [-1.49673317,  1.89851488, -1.60035566],
        [-0.32198552, -0.14122463, -0.97424703]],

       [[ 0.79233256, -0.30162618,  0.79337582],
        [-1.21627259, -1.86678351,  0.1504765 ],
        [-0.57314735,  0.71225377, -1.66290906]],

       [[-0.7793293 ,  1.24704041,  0.08470606],
        [ 0.14248566, -0.8502474 , -0.51205879],
        [ 0.82616699, -0.04450848,  0.21357293]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [26]:
x=np.random.randn(100).reshape(10,10)
print(x)
print("minimum:",x.min())
print("max:",x.max())

[[-7.84241071e-01 -2.80678152e-01  1.13084936e+00 -7.56664661e-02
  -7.97338058e-01  4.65163014e-01 -5.82235285e-01 -3.04552374e-01
  -6.36733219e-01  8.51200618e-02]
 [-1.29576543e-01 -1.23700570e+00  2.00781158e-01 -2.03575627e-01
   1.51341482e+00 -7.96002343e-01 -2.24828545e+00 -6.35358879e-01
  -3.67308815e-01  7.51065347e-01]
 [-1.15244572e+00  5.32206273e-01  5.78696708e-01 -8.55448495e-01
   1.03379669e+00  3.30771879e-01  1.00249385e-01  7.65626240e-01
   2.03024250e-01 -1.24782332e-01]
 [-5.19581948e-01  8.79438609e-02  1.49289860e+00 -1.85997398e+00
  -4.35077344e-01  6.47962235e-01 -1.49476323e+00  1.49809232e-01
  -6.10323503e-01  9.43214060e-01]
 [-5.35988686e-02 -5.02386195e-01  5.04735825e-01  8.75142431e-01
  -3.99672306e-01 -1.76297355e+00 -8.25621399e-01 -2.72807702e-01
   3.42931384e-01  7.46330238e-01]
 [ 1.25827304e+00 -3.25745013e-01 -4.25206941e-01 -1.46847393e-01
   4.91834731e-01 -2.77106191e-01 -5.18643430e-01  5.87771739e-01
   8.22892539e-01  7.10558328e-01

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [27]:
x=np.random.randn(30)
x.mean()

0.06329096462664026

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [31]:
x=np.ones((5,5))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [35]:
x=np.ones((3,3))
x=np.pad(x,1,constant_values=0)
x

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [43]:
a=np.array([1,2,3,4])
a=np.diag(a)
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [46]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [56]:
x=np.random.rand(336).reshape(6,7,8)
x
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [54]:
x=np.array([[0,1],[1,0]])
np.tile(x,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [63]:
x=np.random.randn(25).reshape(5,5)
x_min,x_max=x.min(),x.max()
x=(x-x_min)/(x_max-x_min)
x

array([[0.23448266, 0.7537882 , 0.46835684, 0.54005943, 0.34500323],
       [0.89967529, 0.56019772, 0.34444655, 0.78952115, 0.21925068],
       [0.88403307, 0.7087371 , 0.12624662, 0.54477708, 0.75062866],
       [0.        , 0.56782288, 0.96536834, 0.47533637, 0.38409602],
       [0.56247852, 0.6173059 , 0.35343335, 1.        , 0.37092356]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [64]:
RGBA=np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),("alpha",np.uint8)])
x=np.array([2,3,4,5],dtype=RGBA)
x

array([(2, 2, 2, 2), (3, 3, 3, 3), (4, 4, 4, 4), (5, 5, 5, 5)],
      dtype=[('red', 'u1'), ('green', 'u1'), ('blue', 'u1'), ('alpha', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [66]:
x=np.random.randn(5*3).reshape(5,3)
y=np.random.randn(3*2).reshape(3,2)
np.dot(x,y)

array([[-0.8429619 ,  1.43276551],
       [-1.62674624,  0.01813681],
       [ 0.06771958,  0.25274345],
       [ 0.32016213,  0.3873592 ],
       [ 1.00973062, -0.00229179]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [73]:
x=np.arange(10)
x[(x>=3) & (x<=8)]

array([3, 4, 5, 6, 7, 8])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [74]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [75]:
Z**Z,Z/1/1

NameError: name 'Z' is not defined

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [76]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-76-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-76-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [78]:
x=np.random.randn(4*4).reshape(4,4)
np.round(x,2)

array([[ 1.56,  0.94, -0.26,  0.95],
       [-0.21,  1.41,  0.86,  0.52],
       [-0.15,  0.76,  0.54,  0.28],
       [-0.78,  0.06, -0.53,  0.92]])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [79]:
x=np.array([1,2,3,4,5])
y=np.array([1,3,6,8,9])
np.intersect1d(x,y)

array([1, 3])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [81]:
False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [82]:
yesterday=np.datetime64('today',"D")-np.timedelta64(1,"D")
tommorow=np.datetime64("today","D")+np.timedelta64(1,"D")
today=np.datetime64('today','D')
print(yesterday,today,tommorow)

2021-09-21 2021-09-22 2021-09-23


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [87]:
x=np.arange('2021-7','2021-8',dtype='datetime64[D]')
x

ValueError: Error parsing datetime string "2021-7" at position 5

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [88]:
A=np.random.randn(9).reshape(3,3)
B=np.random.randn(9).reshape(3,3)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.dot(A,B)

array([[-0.26720417,  1.07165441, -1.35978307],
       [ 0.18389953, -0.46921006, -1.22415006],
       [-0.60240084,  1.14095742, -1.03921477]])

'#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [96]:
x=np.random.uniform(2,10,15)
print(np.floor(x))
print(np.ceil(x))
print(x.astype('int'))
print(np.trunc(x))

[5. 8. 4. 5. 8. 8. 9. 5. 7. 3. 6. 8. 2. 9. 2.]
[ 6.  9.  5.  6.  9.  9. 10.  6.  8.  4.  7.  9.  3. 10.  3.]
[5 8 4 5 8 8 9 5 7 3 6 8 2 9 2]
[5. 8. 4. 5. 8. 8. 9. 5. 7. 3. 6. 8. 2. 9. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [98]:
x=np.zeros((5,5))
x+=np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [102]:
def it():
    for x in range(10):
        yield x

x=np.fromiter(it(),dtype=float,count=-1)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [103]:
x=np.linspace(0,1,num=10,endpoint=False)
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [109]:
x=np.random.rand(10)
x.sort()
x

array([0.06787077, 0.12233363, 0.27133243, 0.30897262, 0.36482497,
       0.42143471, 0.53508446, 0.60765242, 0.68665651, 0.71233047])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [112]:
x=np.arange(10)
np.add.reduce(x)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [121]:
A=np.random.randint(1,5,5)
B=np.random.randint(1,5,5)
print(A,B)
print(np.allclose(A,B))
print(np.array_equal(A,B))

[1 1 3 3 1] [2 2 2 4 3]
False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [128]:
x=np.ones(10)
x.flags.writeable=False
x[3]=2

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [129]:
x= np.random.randint(0,9,(10,2))
y,z= x[:,0], x[:,1]
a = np.sqrt(y**2+z**2)
b = np.arctan2(y,z)
pole = np.c_[a,b]
print(pole)

[[5.         0.        ]
 [2.23606798 1.10714872]
 [6.40312424 0.89605538]
 [7.21110255 0.98279372]
 [4.47213595 1.10714872]
 [7.07106781 1.42889927]
 [3.16227766 0.32175055]
 [5.         0.92729522]
 [2.23606798 1.10714872]
 [8.94427191 1.10714872]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [137]:
x=np.random.randint(0,10,10)
print(x)
x[x.argmax()]=0
x


[7 4 1 5 9 8 8 8 7 1]


array([7, 4, 1, 5, 0, 8, 8, 8, 7, 1])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [142]:
A=np.zeros((5,5),[('x',float),('y',float)])
print(A)
A['x'],A['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
A

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]


array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [146]:
x=np.arange(8)
y=np.arange(8,16)
print(x,y)
c=1/np.subtract.outer(x,y)
c

[0 1 2 3 4 5 6 7] [ 8  9 10 11 12 13 14 15]


array([[-0.125     , -0.11111111, -0.1       , -0.09090909, -0.08333333,
        -0.07692308, -0.07142857, -0.06666667],
       [-0.14285714, -0.125     , -0.11111111, -0.1       , -0.09090909,
        -0.08333333, -0.07692308, -0.07142857],
       [-0.16666667, -0.14285714, -0.125     , -0.11111111, -0.1       ,
        -0.09090909, -0.08333333, -0.07692308],
       [-0.2       , -0.16666667, -0.14285714, -0.125     , -0.11111111,
        -0.1       , -0.09090909, -0.08333333],
       [-0.25      , -0.2       , -0.16666667, -0.14285714, -0.125     ,
        -0.11111111, -0.1       , -0.09090909],
       [-0.33333333, -0.25      , -0.2       , -0.16666667, -0.14285714,
        -0.125     , -0.11111111, -0.1       ],
       [-0.5       , -0.33333333, -0.25      , -0.2       , -0.16666667,
        -0.14285714, -0.125     , -0.11111111],
       [-1.        , -0.5       , -0.33333333, -0.25      , -0.2       ,
        -0.16666667, -0.14285714, -0.125     ]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [147]:
print(np.iinfo(dtype).min)

ValueError: Invalid integer data type 'O'.

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [149]:
np.set_printoptions(threshold=np.nan)
x=np.zeros((5,5))
x

ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [156]:
x=np.arange(30)
y=np.random.randint(0,30)
print(x,y)
n=(np.abs(x-y)).argmin()
x[n]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 25


25

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [158]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),('color', [ ('red', float, 1),('green', float, 1),('blue', float, 1)])])

Z

<ipython-input-158-3e13612e2cb0>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),('color', [ ('red', float, 1),('green', float, 1),('blue', float, 1)])])


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('red', '<f8'), ('green', '<f8'), ('blue', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [159]:
Z = np.random.random((10,2))

X,Y = np.atleast_2d(Z[:,0], Z[:,1])

B = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)

B

array([[0.        , 0.44686524, 0.53109406, 0.50207385, 0.51550409,
        0.71698058, 0.20288674, 0.16213923, 0.66223451, 0.62908702],
       [0.44686524, 0.        , 0.77581629, 0.43201106, 0.06888386,
        0.79445119, 0.24405894, 0.51599602, 0.7924119 , 0.35052886],
       [0.53109406, 0.77581629, 0.        , 0.44458965, 0.82461148,
        0.30057674, 0.61814005, 0.67548841, 0.20811889, 0.6853726 ],
       [0.50207385, 0.43201106, 0.44458965, 0.        , 0.45490287,
        0.36785136, 0.4198939 , 0.65671945, 0.38389163, 0.24082383],
       [0.51550409, 0.06888386, 0.82461148, 0.45490287, 0.        ,
        0.82198743, 0.31279838, 0.58346603, 0.82712229, 0.33485768],
       [0.71698058, 0.79445119, 0.30057674, 0.36785136, 0.82198743,
        0.        , 0.72369505, 0.87758626, 0.09448184, 0.57220666],
       [0.20288674, 0.24405894, 0.61814005, 0.4198939 , 0.31279838,
        0.72369505, 0.        , 0.29054872, 0.6932681 , 0.47463778],
       [0.16213923, 0.51599602, 0.6754884

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [160]:
X = np.arange(10, dtype=np.int32)

X = X.astype(np.float32, copy=False)

print(X)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [164]:
x=np.arange(9).reshape(3,3)
print(x)
for index,value in np.ndenumerate(x):
    print(index,value)
for index in np.ndindex(x.shape):
    print(index,x[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [165]:
n = 10
p = 3
x = np.zeros((n,n))
np.put(x, np.random.choice(range(n*n), p, replace=False),1)
print(x)

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [169]:
x = np.random.randn(5, 10)

x = x - x.mean(axis=1, keepdims=True)
x

array([[ 0.57267901,  0.01203247,  0.15987534,  1.46122918,  0.23127994,
        -0.47764384, -0.95606037,  0.4084505 , -0.58481891, -0.82702332],
       [ 0.36581346, -1.41400584,  0.89050714,  0.56608992,  0.04028046,
         1.10856181,  0.03154153, -0.97280679, -0.68041816,  0.06443645],
       [ 0.28395733,  1.30129046, -0.15674432, -0.50664117,  0.61528117,
         0.89251247, -0.3498126 , -1.07009994, -1.14925846,  0.13951507],
       [-1.25068827, -0.17524719, -1.02847978,  0.54057032,  0.60965369,
         0.06419328,  0.48124452, -0.44525091,  0.03792349,  1.16608086],
       [ 0.79923143,  0.97575322,  0.12375096, -0.08728514,  1.07631806,
         0.30704273, -0.25416071, -0.13354595, -1.44975139, -1.35735321]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [171]:
x=np.random.randint(0,10,(3,3))
print(x)
print(z[x[:,1].argsort()])

[[0 3 1]
 [8 9 4]
 [8 5 7]]
[5 4 1]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [174]:
x=np.random.randint(0,3,(3,3))
print((~x.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
x = np.random.uniform(0,1,10)
y = 0.5
a = x.flat[np.abs(x-y).argmin()]
a

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [177]:
x = np.ones(10)
print(x)

y = np.random.randint(0,len(x),20)
print(y)
z += np.bincount(y, minlength=len(x))

print(z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3 6 5 5 4 8 4 1 5 3 0 6 8 6 1 4 1 8 5 2]
[ 9  6 12 14  9  8  8 10  6  6]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [181]:
x = [1,2,3,4,5,6]
y = [1,3,9,3,4,1]
A = np.bincount(x,y)
print(A)

[0. 1. 3. 9. 3. 4. 1.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [180]:
i,j=16,16

x=np.random.randint(1,5,(i,j,3)).astype(np.ubyte)

A = x[...,0]*256*256 + x[...,1]*256 +x[...,2]

n = len(np.unique(A))

print(np.unique(x))

[1 2 3 4]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [185]:
A = np.random.randint(0,10,(3,4,5,4))
print(A)
s = A.sum(axis=(-2,-1))
s

[[[[9 2 8 2]
   [7 0 6 8]
   [3 2 6 7]
   [7 5 7 9]
   [3 0 5 8]]

  [[4 8 2 7]
   [3 6 1 1]
   [4 4 7 0]
   [0 9 7 0]
   [8 0 8 0]]

  [[7 6 8 3]
   [6 2 2 7]
   [9 5 7 3]
   [8 0 8 0]
   [9 5 7 1]]

  [[7 9 2 9]
   [8 1 0 4]
   [9 4 1 0]
   [6 7 9 9]
   [5 9 0 2]]]


 [[[9 6 6 5]
   [3 7 6 4]
   [9 0 6 1]
   [4 8 0 8]
   [7 3 8 5]]

  [[5 1 3 3]
   [3 0 6 3]
   [2 0 4 1]
   [5 6 1 7]
   [4 8 9 7]]

  [[6 5 0 5]
   [5 2 1 8]
   [7 2 2 6]
   [0 0 5 2]
   [5 1 1 6]]

  [[5 7 1 6]
   [5 5 7 6]
   [9 2 1 6]
   [3 0 4 8]
   [0 6 8 6]]]


 [[[3 2 9 0]
   [6 5 1 5]
   [5 1 2 1]
   [6 4 1 3]
   [2 7 6 5]]

  [[6 2 6 2]
   [6 7 9 8]
   [0 0 4 8]
   [9 8 7 0]
   [8 9 1 0]]

  [[8 5 1 9]
   [0 3 6 3]
   [8 8 8 6]
   [5 9 3 3]
   [8 2 4 8]]

  [[9 6 0 5]
   [0 7 9 9]
   [3 2 6 1]
   [8 5 4 8]
   [5 3 0 5]]]]


array([[104,  79, 103, 101],
       [105,  78,  69,  95],
       [ 74, 100, 107,  95]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [186]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
D_means

array([0.49541554, 0.54937532, 0.63305995, 0.50982065, 0.4937529 ,
       0.61213292, 0.41629326, 0.61089501, 0.40594549, 0.62213658])

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [188]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A,B)
np.diag(np.dot(A, B))

[[0.51983014 0.19209341 0.79933501 0.57782275 0.14297208]
 [0.10498476 0.72138871 0.25056449 0.16321478 0.94969209]
 [0.56393479 0.48750942 0.47268081 0.37798814 0.95021317]
 [0.90108482 0.20388684 0.09686896 0.32220466 0.07096434]
 [0.5587993  0.40200246 0.51765989 0.7220669  0.4712986 ]] [[0.84214113 0.88031835 0.48931297 0.79164047 0.00378842]
 [0.65504474 0.56486689 0.75040566 0.88700936 0.22606651]
 [0.07156111 0.78427466 0.88349327 0.5262814  0.76342165]
 [0.87617699 0.98596071 0.53528719 0.03950385 0.41446729]
 [0.16628275 0.85442867 0.33091343 0.54233083 0.36549392]]


array([1.15085021, 1.6687875 , 1.57615126, 0.99637955, 0.95971891])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [189]:
x=np.array([1,2,3,4,5])
n= 3
Z=np.zeros(len(x)+(len(x)-1)*(n))
Z[::n+1] = x
print(Z)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [194]:
A=np.ones((5,5,3))
B=np.ones((5,5))*3
print(A * B[:,:,None])

[[[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [196]:
A=np.arange(25).reshape(5,5)
print(A)
A[[0,1]]=A[[1,0]]
A

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [201]:
x=np.random.randint(0,100,(10,3))
print(x)
A = np.roll(x.repeat(2,axis=1),-1,axis=1)
print(A)
A=A.reshape(len(A)*3,2)
print(A)
A=np.sort(A,axis=1)
print(A)
B=A.view( dtype=[('p0',A.dtype),('p1',A.dtype)] )

B=np.unique(B)
B

[[63 35 11]
 [93 62 68]
 [79 16 37]
 [85 45 38]
 [24 61 91]
 [55  1 99]
 [63 63 91]
 [45 64 78]
 [37 72 27]
 [99 76 42]]
[[63 35 35 11 11 63]
 [93 62 62 68 68 93]
 [79 16 16 37 37 79]
 [85 45 45 38 38 85]
 [24 61 61 91 91 24]
 [55  1  1 99 99 55]
 [63 63 63 91 91 63]
 [45 64 64 78 78 45]
 [37 72 72 27 27 37]
 [99 76 76 42 42 99]]
[[63 35]
 [35 11]
 [11 63]
 [93 62]
 [62 68]
 [68 93]
 [79 16]
 [16 37]
 [37 79]
 [85 45]
 [45 38]
 [38 85]
 [24 61]
 [61 91]
 [91 24]
 [55  1]
 [ 1 99]
 [99 55]
 [63 63]
 [63 91]
 [91 63]
 [45 64]
 [64 78]
 [78 45]
 [37 72]
 [72 27]
 [27 37]
 [99 76]
 [76 42]
 [42 99]]
[[35 63]
 [11 35]
 [11 63]
 [62 93]
 [62 68]
 [68 93]
 [16 79]
 [16 37]
 [37 79]
 [45 85]
 [38 45]
 [38 85]
 [24 61]
 [61 91]
 [24 91]
 [ 1 55]
 [ 1 99]
 [55 99]
 [63 63]
 [63 91]
 [63 91]
 [45 64]
 [64 78]
 [45 78]
 [37 72]
 [27 72]
 [27 37]
 [76 99]
 [42 76]
 [42 99]]


array([( 1, 55), ( 1, 99), (11, 35), (11, 63), (16, 37), (16, 79),
       (24, 61), (24, 91), (27, 37), (27, 72), (35, 63), (37, 72),
       (37, 79), (38, 45), (38, 85), (42, 76), (42, 99), (45, 64),
       (45, 78), (45, 85), (55, 99), (61, 91), (62, 68), (62, 93),
       (63, 63), (63, 91), (64, 78), (68, 93), (76, 99)],
      dtype=[('p0', '<i8'), ('p1', '<i8')])

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)