In [ ]:
#Data.csv

**Step 1: Importing the libraries**

In [7]:
import pandas as pd
import numpy as p
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder,StandardScaler,LabelEncoder


In [9]:
data=pd.read_csv("/Users/alok.g.v/Desktop/python practice/Guvi Task/Task7/Assignment11_to_16/Data.csv")
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

**Step 2: Importing dataset**

**Step 3: Handling the missing data**

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [10]:
data['Age']=data['Age'].fillna((data['Age'].mean()))
data['Salary']=data['Salary'].fillna((data['Salary'].mean()))
data

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

**Step 4: Encoding categorical data**

In [13]:
le=LabelEncoder()

data['Purchased']=le.fit_transform(data['Purchased'])
data

Country        Age        Salary  Purchased
0   France  44.000000  72000.000000          0
1    Spain  27.000000  48000.000000          1
2  Germany  30.000000  54000.000000          0
3    Spain  38.000000  61000.000000          0
4  Germany  40.000000  63777.777778          1
5   France  35.000000  58000.000000          1
6    Spain  38.777778  52000.000000          0
7   France  48.000000  79000.000000          1
8  Germany  50.000000  83000.000000          0
9   France  37.000000  67000.000000          1

**Step 5: Creating a dummy variable**

In [14]:
country_dum=pd.get_dummies(data['Country'],prefix='Country')
data=pd.concat([data,country_dum],axis=1)
data

Country        Age        Salary  Purchased  Country_France  \
0   France  44.000000  72000.000000          0               1   
1    Spain  27.000000  48000.000000          1               0   
2  Germany  30.000000  54000.000000          0               0   
3    Spain  38.000000  61000.000000          0               0   
4  Germany  40.000000  63777.777778          1               0   
5   France  35.000000  58000.000000          1               1   
6    Spain  38.777778  52000.000000          0               0   
7   France  48.000000  79000.000000          1               1   
8  Germany  50.000000  83000.000000          0               0   
9   France  37.000000  67000.000000          1               1   

   Country_Germany  Country_Spain  
0                0              0  
1                0              1  
2                1              0  
3                0              1  
4                1              0  
5                0              0  
6                0              1  
7                0              0  
8                1              0  
9                0              0

**Step 6: Splitting the datasets into training sets and Test sets**

In [19]:
X=data[['Age','Salary','Country_France','Country_Germany','Country_Spain']]
y=data[['Purchased']]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)
X_train.shape

(7, 5)

**Step 7: Feature Scaling**

In [24]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
print(X_train)
print('\n')
X_test=scaler.fit_transform(X_test)
print(X_test)

[[-0.51963886 -0.48609736 -0.63245553 -0.8660254   1.58113883]
 [-0.20025107 -0.23590019 -0.63245553  1.15470054 -0.63245553]
 [ 1.07730008  1.13518031  1.58113883 -0.8660254  -0.63245553]
 [-1.79719001 -1.11659424 -0.63245553  1.15470054 -0.63245553]
 [-0.3954325  -1.2967362  -0.63245553 -0.8660254   1.58113883]
 [ 0.4385245   0.50468344  1.58113883 -0.8660254  -0.63245553]
 [ 1.39668786  1.49546424 -0.63245553  1.15470054 -0.63245553]]


[[-1.38873015 -1.24565666 -1.41421356  0.          1.41421356]
 [ 0.46291005  0.04295368  0.70710678  0.         -0.70710678]
 [ 0.9258201   1.20270298  0.70710678  0.         -0.70710678]]
